Repository victoricoma/front-helpr, pull requests merged in 2022-08, with the labels that each got.

#3 Alteração da cor de fundo de Login
  src/app/components/login/login.component.scss
  src/index.html
Labels: bug

#22 Melhoria login
  src/app/components/login/login.component.html
  src/app/components/login/login.component.scss
Labels: enhancement

#24 implementação do snack sobre politica de cookies
  src/app/components/login/login.component.ts
  src/app/shared/material/material.module.ts
  src/styles.scss
Labels: documentation, enhancement
