Repository victoricoma/front-helpr, pull requests merged in 2022-09, with the labels that each got.

#30 Adic;ao de ChatBot à página login
  src/app/components/login/login.component.html
  src/app/components/login/login.module.ts
  src/index.html
  src/styles.scss
Labels: documentation, enhancement

#34 Adição de tooltips nos botões existentes até build v1.32
  src/app/components/chamados/chamados.component.html
  src/app/components/chamados/children/chamado-create/chamado-create.component.html
  src/app/components/chamados/children/chamado-details/chamado-details.component.html
  src/app/components/chamados/children/chamado-update/chamado-update.component.html
  src/app/components/clientes/children/cliente-create/cliente-create.component.html
  src/app/components/clientes/children/cliente-update/cliente-update.component.html
  src/app/components/clientes/clientes.component.html
  src/app/components/tecnicos/children/tecnico-create/tecnico-create.component.html
  src/app/components/tecnicos/children/tecnico-update/tecnico-update.component.html
  src/app/components/tecnicos/tecnicos.component.html
Labels: documentation, enhancement

#35 Adição de dialog de cadastro de clientes futuros.
  src/app/app.component.html
  src/app/components/login/children/clientes-futuros/clientes-futuros.component.html
  src/app/components/login/children/clientes-futuros/clientes-futuros.component.scss
  src/app/components/login/children/clientes-futuros/clientes-futuros.component.spec.ts
  src/app/components/login/children/clientes-futuros/clientes-futuros.component.ts
  src/app/components/login/login.component.html
  src/app/components/login/login.component.scss
  src/app/components/login/login.component.ts
  src/app/components/login/login.module.ts
  src/app/models/clientes-futuros.ts
Labels: documentation, enhancement

#38 Adição de ícones no status do chamado.
  src/app/components/chamados/chamados.component.html
  src/app/components/chamados/chamados.component.scss
  src/app/components/chamados/chamados.component.ts
Labels: enhancement

#40 Implanatar ProgressBar em tabelas
  src/app/components/chamados/chamados.component.html
  src/app/components/chamados/chamados.component.ts
  src/app/components/clientes/clientes.component.html
  src/app/components/clientes/clientes.component.ts
  src/app/components/tecnicos/tecnicos.component.html
  src/app/components/tecnicos/tecnicos.component.ts
  src/app/shared/material/material.module.ts
Labels: documentation, enhancement

#41 Melhoria visual no formulário de tecnico
  src/app/components/tecnicos/children/tecnico-create/tecnico-create.component.html
  src/app/components/tecnicos/children/tecnico-create/tecnico-create.component.scss
  src/app/components/tecnicos/tecnicos.component.html
  src/app/components/tecnicos/tecnicos.component.scss
Labels: documentation, enhancement

#42 Adição de melhorias visuais e acessibilidade na tabela de clientes
  src/app/components/clientes/clientes.component.html
  src/app/components/clientes/clientes.component.scss
Labels: documentation, enhancement

#43 Adição de filtro a lista de menu e inserção imagem
  src/app/components/nav-bar/nav-bar.component.html
  src/app/components/nav-bar/nav-bar.component.scss
  src/app/components/nav-bar/nav-bar.component.ts
Labels: documentation, enhancement

#46 botão de trabalhe conosco e form de cadastro
  src/app/components/login/children/trabalhe-conosco-form/trabalhe-conosco-form.component.html
  src/app/components/login/children/trabalhe-conosco-form/trabalhe-conosco-form.component.scss
  src/app/components/login/children/trabalhe-conosco-form/trabalhe-conosco-form.component.spec.ts
  src/app/components/login/children/trabalhe-conosco-form/trabalhe-conosco-form.component.ts
  src/app/components/login/children/trabalhe-conosco/trabalhe-conosco.component.html
  src/app/components/login/children/trabalhe-conosco/trabalhe-conosco.component.scss
  src/app/components/login/children/trabalhe-conosco/trabalhe-conosco.component.spec.ts
  src/app/components/login/children/trabalhe-conosco/trabalhe-conosco.component.ts
  src/app/components/login/login.component.html
  src/app/components/login/login.component.scss
  src/app/components/login/login.component.ts
  src/app/components/login/login.module.ts
  src/app/models/tecnicos-futuros.ts
Labels: documentation, enhancement

#49 Adição de icones de prioridade em chamados.
  src/app/components/chamados/chamados.component.html
  src/app/components/chamados/chamados.component.scss
  src/app/components/chamados/chamados.component.ts
Labels: enhancement

#51 Melhorias visuais do formulario de Cliente.
  src/app/components/clientes/children/cliente-create/cliente-create.component.html
  src/app/components/clientes/children/cliente-create/cliente-create.component.scss
Labels: documentation, enhancement

#52 Alteração formulario de login e correção da imagem
  src/app/components/login/login.component.html
  src/app/components/login/login.component.scss
Labels: documentation, enhancement

#53 Adição do timer de expiração de sessão do token
  src/app/services/auth.service.ts
Labels: documentation, enhancement

#54 Ajuste padronizado de layouts em todas as tabelas
  src/app/components/clientes/clientes.component.html
  src/app/components/tecnicos/tecnicos.component.html
Labels: bug

#55 Respansividade Pagina login
  src/app/components/login/login.component.html
  src/app/components/login/login.component.scss
Labels: bug

#60 Adição do layout de dashboard para técnico
  src/app/components/home/home.module.ts
  src/app/components/home/tecnico/dashboard/dashtec/dashtec.component.html
  src/app/components/home/tecnico/dashboard/dashtec/dashtec.component.scss
  src/app/components/home/tecnico/dashboard/dashtec/dashtec.component.spec.ts
  src/app/components/home/tecnico/dashboard/dashtec/dashtec.component.ts
  src/app/components/home/tecnico/dashboard/tecnico-dashboard.component.html
Labels: documentation, enhancement

#64 Adição de dialog auxiliar na tabela chamado para técnico e cliente.
  src/app/components/chamados/chamados.component.html
  src/app/components/chamados/chamados.component.ts
  src/app/components/chamados/chamados.module.ts
  src/app/components/chamados/children/chamado-clients/chamado-clients.component.html
  src/app/components/chamados/children/chamado-clients/chamado-clients.component.scss
  src/app/components/chamados/children/chamado-clients/chamado-clients.component.spec.ts
  src/app/components/chamados/children/chamado-clients/chamado-clients.component.ts
  src/app/components/chamados/children/chamado-tecnicos/chamado-tecnicos.component.html
  src/app/components/chamados/children/chamado-tecnicos/chamado-tecnicos.component.scss
  src/app/components/chamados/children/chamado-tecnicos/chamado-tecnicos.component.spec.ts
  src/app/components/chamados/children/chamado-tecnicos/chamado-tecnicos.component.ts
  src/app/shared/material/material.module.ts
Labels: documentation, enhancement

#66 Melhorias visual no formulário de cadastro de chamados.
  src/app/components/chamados/chamados.component.html
  src/app/components/chamados/chamados.component.scss
  src/app/components/chamados/children/chamado-create/chamado-create.component.html
  src/app/components/chamados/children/chamado-create/chamado-create.component.scss
Labels: enhancement

#67 Adição de stepper ao cadastro de futuros clientes
  src/app/components/login/children/clientes-futuros/clientes-futuros.component.html
  src/app/components/login/children/clientes-futuros/clientes-futuros.component.scss
  src/app/components/login/children/clientes-futuros/clientes-futuros.component.ts
  src/app/components/login/login.component.ts
  src/app/shared/material/material.module.ts
Labels: documentation, enhancement

#69 Respansividade para todas as páginas com tabelas.
  src/app/components/chamados/chamados.component.html
  src/app/components/chamados/chamados.component.scss
  src/app/components/clientes/clientes.component.html
  src/app/components/clientes/clientes.component.scss
  src/app/components/tecnicos/tecnicos.component.html
  src/app/components/tecnicos/tecnicos.component.scss
Labels: bug

#72 Dialogo Tela de Login
  src/app/components/login/children/promocoes/promocoes.component.html
  src/app/components/login/children/promocoes/promocoes.component.scss
  src/app/components/login/children/promocoes/promocoes.component.spec.ts
  src/app/components/login/children/promocoes/promocoes.component.ts
  src/app/components/login/login.component.ts
  src/app/components/login/login.module.ts
Labels: documentation, enhancement

#74 Adição de tooltips e correção de escrita.
  src/app/components/chamados/chamados.component.html
  src/app/components/nav-bar/nav-bar.component.html
  src/app/components/tecnicos/tecnicos.component.html
Labels: bug, enhancement

#76 Correção de bug do tema escuro na tela de login.
  src/app/components/login/login.component.html
  src/app/components/login/login.component.scss
  src/app/components/login/login.component.ts
  src/app/components/nav-bar/nav-bar.component.ts
  src/app/utils/exit/exit.component.ts
  src/assets/img/ext1.png
Labels: bug

#78 Sistema de Tabs na recepção Admin
  src/app/components/home/admin/dashboard/admin-dashboard.component.html
  src/app/shared/material/material.module.ts
Labels: documentation

#79 Implementação de PWA ao helpr
  angular.json
  ngsw-config.json
  package-lock.json
  package.json
  src/app/app.module.ts
  src/app/components/home/home.component.ts
  src/index.html
  src/manifest.webmanifest
Labels: documentation, enhancement

#81 Implementação dashboardadmin
  src/app/components/home/admin/dashboard/admin-dashboard.component.html
  src/app/components/home/admin/dashboard/admin-dashboard.component.scss
  src/app/components/home/admin/dashboard/dashadmin/dashadmin.component.html
  src/app/components/home/admin/dashboard/dashadmin/dashadmin.component.scss
  src/app/components/home/admin/dashboard/dashadmin/dashadmin.component.spec.ts
  src/app/components/home/admin/dashboard/dashadmin/dashadmin.component.ts
  src/app/components/home/home.module.ts
  src/app/components/nav-bar/nav-bar.component.ts
  src/app/shared/material/material.module.ts
Labels: documentation, enhancement

#83 Adição de menu ambiente de usuário logado
  src/app/app-routing.module.ts
  src/app/components/nav-bar/nav-bar.component.html
  src/app/components/nav-bar/nav-bar.component.scss
  src/app/components/perfil/perfil.component.html
  src/app/components/perfil/perfil.component.scss
  src/app/components/perfil/perfil.component.spec.ts
  src/app/components/perfil/perfil.component.ts
  src/app/components/perfil/perfil.module.ts
  src/app/shared/material/material.module.ts
  src/app/shared/pages/pages.module.ts
Labels: documentation, enhancement

#84 Adição da rota de home, para cada role.
  src/app/components/home/home.component.ts
Labels: documentation, enhancement

#85 criação tela de chamados do cliente logado
  src/app/components/home/cliente/dashboard/cliente-dashboard.component.html
  src/app/components/home/cliente/dashboard/cliente-dashboard.component.scss
  src/app/components/home/cliente/dashboard/cliente-dashboard.component.ts
  src/app/components/login/login.component.ts
  src/app/models/chamados-cliente.ts
  src/app/models/tecnico.ts
  src/app/services/chamados-cliente.service.spec.ts
  src/app/services/chamados-cliente.service.ts
Labels: documentation, enhancement

#88 Mudança formulário técnico e cliente
  src/app/components/clientes/children/cliente-update/cliente-update.component.html
  src/app/components/tecnicos/children/tecnico-update/tecnico-update.component.html
Labels: bug

#89 adição de stepper no form trabalhe conosco
  src/app/components/login/children/trabalhe-conosco-form/trabalhe-conosco-form.component.html
  src/app/components/login/children/trabalhe-conosco-form/trabalhe-conosco-form.component.ts
Labels: documentation, enhancement

#90 Atualização do Layout para ser intuitivo e padrão
  src/app/components/home/tecnico/dashboard/dashtec/dashtec.component.html
  src/app/components/home/tecnico/dashboard/dashtec/dashtec.component.ts
  src/app/components/home/tecnico/dashboard/tecnico-dashboard.component.html
  src/app/shared/pages/pages.module.ts
Labels: bug, documentation

#93 Padronização dos Cards Banner
  src/app/components/chamados/chamados.component.html
  src/app/components/tecnicos/tecnicos.component.html
Labels: bug

#96 "Criação de dialogs para informações relevantes"
  src/app/components/home/admin/dashboard/admin-dashboard.component.html
  src/app/components/home/admin/dashboard/dashadmin/dashadmin.component.html
  src/app/components/home/admin/dashboard/dashadmin/dashadmin.component.scss
  src/app/components/home/admin/dashboard/dashadmin/dashadmin.component.ts
  src/app/components/home/admin/dashboard/dialog-chamados-abertos/dialog-chamados-abertos.component.html
  src/app/components/home/admin/dashboard/dialog-chamados-abertos/dialog-chamados-abertos.component.scss
  src/app/components/home/admin/dashboard/dialog-chamados-abertos/dialog-chamados-abertos.component.spec.ts
  src/app/components/home/admin/dashboard/dialog-chamados-abertos/dialog-chamados-abertos.component.ts
  src/app/components/home/admin/dashboard/dialog-chamados-urgentes/dialog-chamados-urgentes.component.html
  src/app/components/home/admin/dashboard/dialog-chamados-urgentes/dialog-chamados-urgentes.component.scss
  src/app/components/home/admin/dashboard/dialog-chamados-urgentes/dialog-chamados-urgentes.component.spec.ts
  src/app/components/home/admin/dashboard/dialog-chamados-urgentes/dialog-chamados-urgentes.component.ts
  src/app/components/home/home.module.ts
  src/app/components/home/tecnico/dashboard/dashtec/dashtec.component.html
  src/app/components/home/tecnico/dashboard/dashtec/dashtec.component.scss
  src/app/components/home/tecnico/dashboard/dashtec/dashtec.component.ts
  src/app/components/home/tecnico/dashboard/dialog-chamados-tecnico-abertos/dialog-chamados-tecnico-abertos.component.html
  src/app/components/home/tecnico/dashboard/dialog-chamados-tecnico-abertos/dialog-chamados-tecnico-abertos.component.scss
  src/app/components/home/tecnico/dashboard/dialog-chamados-tecnico-abertos/dialog-chamados-tecnico-abertos.component.spec.ts
  src/app/components/home/tecnico/dashboard/dialog-chamados-tecnico-abertos/dialog-chamados-tecnico-abertos.component.ts
  src/app/components/home/tecnico/dashboard/dialog-chamados-tecnico-urgentes/dialog-chamados-tecnico-urgentes.component.html
  src/app/components/home/tecnico/dashboard/dialog-chamados-tecnico-urgentes/dialog-chamados-tecnico-urgentes.component.scss
  src/app/components/home/tecnico/dashboard/dialog-chamados-tecnico-urgentes/dialog-chamados-tecnico-urgentes.component.spec.ts
  src/app/components/home/tecnico/dashboard/dialog-chamados-tecnico-urgentes/dialog-chamados-tecnico-urgentes.component.ts
  src/app/shared/material/material.module.ts
Labels: documentation, enhancement

#99 Adição de botão na lista de técnicos para mostrar chamados abertos no dia
  src/app/components/tecnicos/children/tecnico-chamados/tecnico-chamados.component.html
  src/app/components/tecnicos/children/tecnico-chamados/tecnico-chamados.component.scss
  src/app/components/tecnicos/children/tecnico-chamados/tecnico-chamados.component.spec.ts
  src/app/components/tecnicos/children/tecnico-chamados/tecnico-chamados.component.ts
  src/app/components/tecnicos/tecnicos.component.html
  src/app/components/tecnicos/tecnicos.component.ts
  src/app/components/tecnicos/tecnicos.module.ts
Labels: documentation, enhancement

#101 Implementação de FAQ para cada perfil
  src/app/app-routing.module.ts
  src/app/faq/faq.component.html
  src/app/faq/faq.component.scss
  src/app/faq/faq.component.spec.ts
  src/app/faq/faq.component.ts
  src/app/faq/faq.module.ts
  src/app/models/faq.ts
  src/app/shared/material/material.module.ts
  src/app/shared/pages/pages.module.ts
Labels: documentation, enhancement

#103 Implementação do sistema de tabs na dashboard tecnico
  src/app/components/home/tecnico/dashboard/dashtec/dashtec.component.html
  src/app/components/home/tecnico/dashboard/dashtec/dashtec.component.scss
Labels: documentation, enhancement

#106 Implementação de cacheamento dos dados
  package-lock.json
  package.json
  src/app/components/chamados/children/chamado-create/chamado-create.component.ts
  src/app/components/clientes/children/cliente-create/cliente-create.component.ts
  src/app/components/tecnicos/children/tecnico-create/tecnico-create.component.ts
  src/app/models/chamado.ts
  src/app/models/cliente.ts
  src/app/models/tecnico.ts
  src/app/services/chamado.service.ts
  src/app/services/cliente.service.ts
  src/app/services/online-offline.service.ts
  src/app/services/tecnico.service.ts
  src/index.html
Labels: documentation, enhancement

#107 Ajustes visuais no nav bar
  src/app/components/home/home.component.html
  src/app/components/nav-bar/nav-bar.component.html
  src/app/components/nav-bar/nav-bar.component.scss
Labels: bug

#108 Aplicação de expasion panel na aba log de ADM.
  src/app/components/home/admin/dashboard/admin-dashboard.component.html
  src/app/components/home/admin/dashboard/dashadmin/dashadmin.component.html
  src/app/components/home/admin/dashboard/logPerfis/log-perfis/log-perfis.component.html
  src/app/components/home/admin/dashboard/logPerfis/log-perfis/log-perfis.component.scss
  src/app/components/home/admin/dashboard/logPerfis/log-perfis/log-perfis.component.spec.ts
  src/app/components/home/admin/dashboard/logPerfis/log-perfis/log-perfis.component.ts
  src/app/components/home/home.module.ts
Labels: documentation, enhancement

#109 Criação da página de informações do usuário logado
  src/app/components/login/login.component.ts
  src/app/components/perfil/perfil.component.html
  src/app/components/perfil/perfil.component.scss
  src/app/components/perfil/perfil.component.ts
  src/app/components/perfil/perfil.module.ts
Labels: documentation, enhancement

#111 Padronização do Menu lateral de Cliente.
  src/app/components/nav-bar/nav-bar.component.ts
Labels: documentation, enhancement

#113 Padronização de dialogos e formulários sem verificação Jwt
  src/app/components/login/children/clientes-futuros/clientes-futuros.component.html
  src/app/components/login/children/clientes-futuros/clientes-futuros.component.scss
  src/app/components/login/children/trabalhe-conosco-form/trabalhe-conosco-form.component.html
  src/app/components/login/children/trabalhe-conosco-form/trabalhe-conosco-form.component.scss
  src/app/components/login/children/trabalhe-conosco-form/trabalhe-conosco-form.component.ts
  src/app/components/login/login.component.ts
Labels: bug

#117 Adição de rotatividade de banners publicitários
  src/app/components/chamados/chamados.component.html
  src/app/components/chamados/chamados.component.ts
  src/app/components/clientes/clientes.component.html
  src/app/components/clientes/clientes.component.ts
  src/app/components/tecnicos/tecnicos.component.html
  src/app/components/tecnicos/tecnicos.component.ts
Labels: bug

#118 Validação de acesso para respectivos perfis.
  src/app/app-routing.module.ts
  src/app/components/nav-bar/nav-bar.component.ts
  src/app/guards/clientes.guard.spec.ts
  src/app/guards/clientes.guard.ts
Labels: enhancement

#122 Ajuste de responsvidade de banner e tabela.
  src/app/components/chamados/children/chamado-create/chamado-create.component.scss
  src/app/components/clientes/children/cliente-create/cliente-create.component.scss
  src/app/components/tecnicos/children/tecnico-create/tecnico-create.component.scss
Labels: documentation, enhancement

#123 Aplicação de filtro de chamados por técnico logado
  src/app/components/home/admin/dashboard/dashadmin/dashadmin.component.ts
  src/app/components/home/admin/dashboard/dialog-chamados-abertos/dialog-chamados-abertos.component.ts
  src/app/components/home/admin/dashboard/dialog-chamados-urgentes/dialog-chamados-urgentes.component.ts
  src/app/components/home/tecnico/dashboard/dashtec/dashtec.component.ts
  src/app/components/home/tecnico/dashboard/dialog-chamados-tecnico-abertos/dialog-chamados-tecnico-abertos.component.ts
  src/app/components/home/tecnico/dashboard/dialog-chamados-tecnico-urgentes/dialog-chamados-tecnico-urgentes.component.ts
Labels: enhancement

#124 Implementação de tabela de log prioridade chamado.
  src/app/components/chamados/chamados.module.ts
  src/app/components/chamados/children/log-prioridade/log-prioridade.component.html
  src/app/components/chamados/children/log-prioridade/log-prioridade.component.scss
  src/app/components/chamados/children/log-prioridade/log-prioridade.component.spec.ts
  src/app/components/chamados/children/log-prioridade/log-prioridade.component.ts
  src/app/components/home/admin/dashboard/admin-dashboard.component.html
  src/app/components/home/home.module.ts
  src/app/models/chamadologPrioridade.ts
  src/app/services/chamado.service.ts
Labels: documentation, enhancement

#125 Adição de tabela de relatórios de técnicos
  src/app/components/home/tecnico/dashboard/dashtec/dashtec.component.html
  src/app/components/home/tecnico/dashboard/dashtec/dashtec.component.scss
  src/app/components/home/tecnico/dashboard/dashtec/dashtec.component.ts
  src/app/models/relatorios-tecnicos.ts
Labels: documentation, enhancement

#128 Tabela para apresentar chamados e pipes
  src/app/components/home/home.module.ts
  src/app/components/home/tecnico/dashboard/dashtec/dashtec.component.html
  src/app/components/home/tecnico/dashboard/dashtec/dashtec.component.scss
  src/app/components/home/tecnico/dashboard/dashtec/dashtec.component.ts
  src/app/pipes/prioridade.pipe.ts
  src/app/pipes/status.pipe.ts
Labels: documentation, enhancement

#130 Adição do checkbox lembrar-me
  src/app/components/login/login.component.html
  src/app/components/login/login.component.ts
Labels: documentation, enhancement

#131 Adição de um gráfico que mostra os chamados do tecnico
  package-lock.json
  package.json
  src/app/components/home/home.module.ts
  src/app/components/home/tecnico/dashboard/dashtec/dashtec.component.html
  src/app/components/home/tecnico/dashboard/grafico-chamados/grafico-chamados.component.html
  src/app/components/home/tecnico/dashboard/grafico-chamados/grafico-chamados.component.scss
  src/app/components/home/tecnico/dashboard/grafico-chamados/grafico-chamados.component.spec.ts
  src/app/components/home/tecnico/dashboard/grafico-chamados/grafico-chamados.component.ts
Labels: documentation, enhancement

#132 Implementação de animação página de login.
  package-lock.json
  package.json
  src/app/components/login/login.component.html
  src/index.html
Labels: documentation, enhancement

#133 Criação do servço de futuros candidatos
  src/app/components/login/children/trabalhe-conosco-form/trabalhe-conosco-form.component.html
  src/app/components/login/children/trabalhe-conosco-form/trabalhe-conosco-form.component.ts
  src/app/services/tecnicosfuturos.service.spec.ts
  src/app/services/tecnicosfuturos.service.ts
Labels: documentation, enhancement

#134 Ajustes complementares de bugs e clean code
  src/app/app-routing.module.ts
  src/app/components/chamados/chamados.component.ts
  src/app/components/clientes/clientes.component.ts
  src/app/components/login/login.component.ts
  src/app/components/tecnicos/tecnicos.component.ts
Labels: bug, documentation

#136 Adição de SnackBar de status online e Offline
  src/app/app.component.ts
Labels: documentation, enhancement

#138 Adição de dialog de logout ao clicar em sair
  src/app/app-routing.module.ts
  src/app/components/nav-bar/logout-dialog/logout-dialog.component.html
  src/app/components/nav-bar/logout-dialog/logout-dialog.component.scss
  src/app/components/nav-bar/logout-dialog/logout-dialog.component.spec.ts
  src/app/components/nav-bar/logout-dialog/logout-dialog.component.ts
  src/app/components/nav-bar/nav-bar.component.html
  src/app/components/nav-bar/nav-bar.component.ts
  src/app/components/nav-bar/nav-bar.module.ts
Labels: documentation, enhancement

#139 Criação chamados urgentes dos ultimos tres dias
  src/app/components/home/admin/dashboard/admin-dashboard.component.html
  src/app/components/home/admin/dashboard/chamado-urgente/chamado-urgente.component.html
  src/app/components/home/admin/dashboard/chamado-urgente/chamado-urgente.component.scss
  src/app/components/home/admin/dashboard/chamado-urgente/chamado-urgente.component.spec.ts
  src/app/components/home/admin/dashboard/chamado-urgente/chamado-urgente.component.ts
  src/app/components/home/home.module.ts
  src/app/models/chamado-urgente.ts
  src/app/services/chamado-urgente.service.spec.ts
  src/app/services/chamado-urgente.service.ts
Labels: documentation, enhancement

#140 Log de troca de status
  src/app/components/chamados/chamados.module.ts
  src/app/components/chamados/children/log-status/log-status.component.html
  src/app/components/chamados/children/log-status/log-status.component.scss
  src/app/components/chamados/children/log-status/log-status.component.spec.ts
  src/app/components/chamados/children/log-status/log-status.component.ts
  src/app/components/home/admin/dashboard/logPerfis/log-perfis/log-perfis.component.html
  src/app/models/chamadoLogStatus.ts
  src/app/services/chamado.service.ts
Labels: documentation, enhancement

#141 Implementação visual do token.
  src/app/components/nav-bar/nav-bar.component.html
  src/app/components/nav-bar/nav-bar.component.scss
  src/app/components/nav-bar/nav-bar.component.ts
  src/app/services/auth.service.ts
Labels: enhancement

#142 Tabela chamado dia atual
  src/app/components/clientes/children/chamados-clientes/chamados-clientes.component.html
  src/app/components/clientes/children/chamados-clientes/chamados-clientes.component.scss
  src/app/components/clientes/children/chamados-clientes/chamados-clientes.component.spec.ts
  src/app/components/clientes/children/chamados-clientes/chamados-clientes.component.ts
  src/app/components/clientes/clientes.component.html
  src/app/components/clientes/clientes.component.ts
  src/app/components/clientes/clientes.module.ts
Labels: documentation, enhancement

#144 Criação de aba urgencias na dash de admin.
  src/app/components/home/admin/dashboard/admin-dashboard.component.html
  src/app/components/home/admin/dashboard/urgencias/urgencias.component.html
  src/app/components/home/admin/dashboard/urgencias/urgencias.component.scss
  src/app/components/home/admin/dashboard/urgencias/urgencias.component.spec.ts
  src/app/components/home/admin/dashboard/urgencias/urgencias.component.ts
  src/app/components/home/home.module.ts
Labels: documentation, enhancement
